import { Lexer } from '../lexer';
import { Parser } from '../parser';
import type { ASTNode, FunctionDefNode, ImportNode } from '../ast';
import { analyzeSemantics } from './semantic';
import { DiagnosticCollector, type Diagnostic } from './diagnostics';
import type { IRModule, IRFunction, IROp } from './ir';
import { irToText } from './ir';

export type CompileOptions = {
  optimize?: boolean;
  target?: 'interpret' | 'ir' | 'js';
};

export type CompileResult = {
  success: boolean;
  ast: ASTNode[];
  diagnostics: Diagnostic[];
  ir?: IRModule;
  output?: string;
  error?: string;
};

function astToIR(ast: ASTNode[]): IRModule {
  const mod: IRModule = {
    name: 'main',
    functions: [],
    structs: [],
    enums: [],
    traits: [],
    interfaces: [],
    imports: [],
  };

  for (const node of ast) {
    if (node.type === 'structDef') mod.structs.push(node.name);
    if (node.type === 'enumDef') mod.enums.push(node.name);
    if (node.type === 'traitDef') mod.traits.push(node.name);
    if (node.type === 'interfaceDef') mod.interfaces.push(node.name);
    if (node.type === 'import') {
      mod.imports.push({ module: node.module, names: node.names });
    }
    if (node.type === 'functionDef') {
      mod.functions.push(functionToIR(node));
    }
  }
  return mod;
}

function functionToIR(fn: FunctionDefNode): IRFunction {
  const body: IROp[] = [{ op: 'label', name: 'entry' }];
  let tmp = 0;
  const next = () => `$t${tmp++}`;

  for (const stmt of fn.body) {
    if (stmt.type === 'return' && stmt.value) {
      const dest = next();
      body.push({ op: 'call', fn: '__expr', args: [], dest });
      body.push({ op: 'return', src: dest });
    } else if (stmt.type === 'assignment') {
      const dest = next();
      body.push({ op: 'const', value: null, dest });
      body.push({ op: 'store', name: stmt.variable, src: dest });
    }
  }
  body.push({ op: 'return' });
  return {
    name: fn.name,
    params: fn.params,
    typeParams: fn.typeParams,
    async: fn.async,
    locals: [],
    body,
  };
}

function optimizeIR(mod: IRModule): IRModule {
  // Foundation: dead label elimination
  return {
    ...mod,
    functions: mod.functions.map((f) => ({
      ...f,
      body: f.body.filter((op, i, arr) => {
        if (op.op !== 'label') return true;
        return arr[i + 1]?.op !== 'label';
      }),
    })),
  };
}

function irToJavaScript(mod: IRModule): string {
  const lines = ['// Generated by TauScript v1.0 compiler', '(function() {'];
  for (const f of mod.functions) {
    const asyncKw = f.async ? 'async ' : '';
    lines.push(`  ${asyncKw}function ${f.name}(${f.params.join(', ')}) {`);
    lines.push('    // IR body omitted — use interpret target for full execution');
    lines.push('  }');
  }
  lines.push('})();');
  return lines.join('\n');
}

export function compile(source: string, options: CompileOptions = {}): CompileResult {
  const diagnostics = new DiagnosticCollector();

  try {
    const lexer = new Lexer(source);
    const tokens = lexer.tokenize();
    const parser = new Parser(tokens);
    const ast = parser.parse();

    const semantic = analyzeSemantics(ast);
    diagnostics.merge(semantic.diagnostics);

    if (diagnostics.hasErrors()) {
      return { success: false, ast, diagnostics: diagnostics.getAll(), error: diagnostics.format() };
    }

    let ir = astToIR(ast);
    if (options.optimize) ir = optimizeIR(ir);

    const result: CompileResult = {
      success: true,
      ast,
      diagnostics: diagnostics.getAll(),
      ir,
    };

    if (options.target === 'ir') {
      result.output = irToText(ir);
    } else if (options.target === 'js') {
      result.output = irToJavaScript(ir);
    }

    return result;
  } catch (e) {
    diagnostics.error(e instanceof Error ? e.message : 'Compilation failed');
    return { success: false, ast: [], diagnostics: diagnostics.getAll(), error: diagnostics.format() };
  }
}

export function compileFile(source: string, target: CompileOptions['target'] = 'interpret') {
  return compile(source, { target, optimize: true });
}
