version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15-alpine
    container_name: taumail-postgres
    environment:
      POSTGRES_DB: taumail
      POSTGRES_USER: taumail
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secure_password_123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - taumail-network

  # Redis for sessions and caching
  redis:
    image: redis:7-alpine
    container_name: taumail-redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redis_password_123}
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - taumail-network

  # Mail server (SMTP)
  postfix:
    image: catatnight/postfix:latest
    container_name: taumail-postfix
    environment:
      maildomain: ${MAIL_DOMAIN:-tauos.org}
      smtp_user: ${SMTP_USER:-admin}:${SMTP_PASSWORD:-secure_smtp_123}
    volumes:
      - ./config/postfix/main.cf:/etc/postfix/main.cf
      - ./config/postfix/master.cf:/etc/postfix/master.cf
      - ./config/postfix/virtual:/etc/postfix/virtual
      - ./config/postfix/virtual.db:/etc/postfix/virtual.db
      - mail_data:/var/mail
      - ./logs/postfix:/var/log/postfix
    ports:
      - "25:25"
      - "587:587"
    restart: unless-stopped
    networks:
      - taumail-network
    depends_on:
      - postgres
      - redis

  # IMAP/POP3 server
  dovecot:
    image: dovemark/dovecot:latest
    container_name: taumail-dovecot
    environment:
      DOVECOT_DOMAIN: ${MAIL_DOMAIN:-tauos.org}
    volumes:
      - ./config/dovecot/dovecot.conf:/etc/dovecot/dovecot.conf
      - ./config/dovecot/conf.d:/etc/dovecot/conf.d
      - mail_data:/var/mail
      - ./logs/dovecot:/var/log/dovecot
    ports:
      - "143:143"
      - "993:993"
      - "110:110"
      - "995:995"
    restart: unless-stopped
    networks:
      - taumail-network
    depends_on:
      - postgres
      - redis

  # Anti-spam and anti-virus
  rspamd:
    image: rspamd/rspamd:latest
    container_name: taumail-rspamd
    volumes:
      - ./config/rspamd/rspamd.conf:/etc/rspamd/rspamd.conf
      - ./config/rspamd/local.d:/etc/rspamd/local.d
      - ./logs/rspamd:/var/log/rspamd
    ports:
      - "11334:11334"
    restart: unless-stopped
    networks:
      - taumail-network

  # Webmail interface
  webmail:
    build:
      context: ./webmail
      dockerfile: Dockerfile
    container_name: taumail-webmail
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://taumail:${POSTGRES_PASSWORD:-secure_password_123}@postgres:5432/taumail
      REDIS_URL: redis://:${REDIS_PASSWORD:-redis_password_123}@redis:6379
      JWT_SECRET: ${JWT_SECRET:-your_jwt_secret_here}
      SMTP_HOST: postfix
      SMTP_PORT: 587
      IMAP_HOST: dovecot
      IMAP_PORT: 993
      MAIL_DOMAIN: ${MAIL_DOMAIN:-tauos.org}
    volumes:
      - ./config/webmail:/app/config
      - ./logs/webmail:/app/logs
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - taumail-network
    depends_on:
      - postgres
      - redis
      - postfix
      - dovecot

  # Admin dashboard
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: taumail-admin
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://taumail:${POSTGRES_PASSWORD:-secure_password_123}@postgres:5432/taumail
      REDIS_URL: redis://:${REDIS_PASSWORD:-redis_password_123}@redis:6379
      JWT_SECRET: ${JWT_SECRET:-your_jwt_secret_here}
    volumes:
      - ./config/admin:/app/config
      - ./logs/admin:/app/logs
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - taumail-network
    depends_on:
      - postgres
      - redis

  # Reverse proxy with SSL
  nginx:
    image: nginx:alpine
    container_name: taumail-nginx
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - taumail-network
    depends_on:
      - webmail
      - admin

  # Monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: taumail-prometheus
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - taumail-network

  grafana:
    image: grafana/grafana:latest
    container_name: taumail-grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3002:3000"
    restart: unless-stopped
    networks:
      - taumail-network
    depends_on:
      - prometheus

volumes:
  postgres_data:
  redis_data:
  mail_data:
  prometheus_data:
  grafana_data:

networks:
  taumail-network:
    driver: bridge 