/** Local Figma-exported assets for pages 12–14 */

export const marketingAssets = {
  shared: {
    logoIcon: '/website/marketing/shared/logo-icon.png',
    github: '/website/marketing/shared/github.svg',
    twitter: '/website/marketing/shared/twitter.svg',
    messageSquare: '/website/marketing/shared/message-square.svg',
  },
  roadmap: {
    timelineLine: '/website/marketing/roadmap/timeline-line.svg',
    check: '/website/marketing/roadmap/check.svg',
    markerCurrent: '/website/marketing/roadmap/marker-current.svg',
    markerUpcoming: '/website/marketing/roadmap/marker-upcoming.svg',
    ellipse: '/website/marketing/roadmap/ellipse.svg',
  },
  download: {
    package: '/website/marketing/download/icon-package.svg',
    download: '/website/marketing/download/icon-download.svg',
    globe: '/website/marketing/download/icon-globe.svg',
    circleX: '/website/marketing/download/icon-circle-x.svg',
    database: '/website/marketing/download/icon-database.svg',
    messageLock: '/website/marketing/download/icon-message-lock.svg',
    terminal: '/website/marketing/download/icon-terminal.svg',
    check: '/website/marketing/download/icon-check.svg',
  },
  startup: {
    hero: '/website/marketing/startup/hero.png',
    founderDevon: '/website/marketing/startup/founder-devon.png',
    founderAlina: '/website/marketing/startup/founder-alina.png',
    database: '/website/marketing/startup/icon-database.svg',
    microchip: '/website/marketing/startup/icon-microchip.svg',
    target: '/website/marketing/startup/icon-target.svg',
    shieldCheck: '/website/marketing/startup/icon-shield-check.svg',
    check: '/website/marketing/startup/icon-check.svg',
  },
  careers: {
    hero: '/website/marketing/careers/hero.png',
    lock: '/website/marketing/careers/icon-lock.svg',
    ruler: '/website/marketing/careers/icon-ruler.svg',
    users: '/website/marketing/careers/icon-users.svg',
    arrowRight: '/website/marketing/careers/icon-arrow-right.svg',
    network: '/website/marketing/careers/icon-network.svg',
    trendingUp: '/website/marketing/careers/icon-trending-up.svg',
    activity: '/website/marketing/careers/icon-activity.svg',
    bookOpen: '/website/marketing/careers/icon-book-open.svg',
  },
  press: {
    featured: '/website/marketing/press/featured.png',
    arrowRight: '/website/marketing/press/icon-arrow-right.svg',
    download: '/website/marketing/press/icon-download.svg',
  },
  contact: {
    globeMap: '/website/marketing/contact/globe-map.png',
    chevronDown: '/website/marketing/contact/icon-chevron-down.svg',
    twitter: '/website/marketing/contact/icon-twitter.svg',
    github: '/website/marketing/contact/icon-github.svg',
    linkedin: '/website/marketing/contact/icon-linkedin.svg',
  },
  hardware: {
    devicesLogo: '/website/marketing/hardware/tau-devices-logo.png',
    phoneRender: '/website/marketing/hardware/phone-render.png',
    laptopRender: '/website/marketing/hardware/laptop-render.png',
    tabletRender: '/website/marketing/hardware/tablet-render.png',
    watchRender: '/website/marketing/hardware/watch-render.png',
    glassRender: '/website/marketing/hardware/glass-render.png',
    divider: '/website/marketing/hardware/divider.svg',
  },
  store: {
    devicesLogo: '/website/marketing/store/tau-devices-logo.png',
    productPhone: '/website/marketing/store/product-phone.png',
    productBook: '/website/marketing/store/product-book.png',
    productTablet: '/website/marketing/store/product-tablet.png',
    productWatch: '/website/marketing/store/product-watch.png',
    productGlass: '/website/marketing/store/product-glass.png',
    accessoriesHero: '/website/marketing/store/product-accessories-hero.png',
    accessory1: '/website/marketing/store/accessory-1.png',
    accessory2: '/website/marketing/store/accessory-2.png',
    accessory3: '/website/marketing/store/accessory-3.png',
    accessory4: '/website/marketing/store/accessory-4.png',
    plus: '/website/marketing/store/icon-plus.svg',
    shieldCheck: '/website/marketing/store/icon-shield-check.svg',
  },
} as const;
