/** Tau website link map — Figma footer/nav labels → live routes */

export const websiteRoutes = {
  home: '/',
  tauCore: '/products/tau-core',
  tauDesktopOs: '/products/tau-desktop-os',
  tauMobileOs: '/products/tau-mobile-os',
  tauPhone: '/products/tau-phone',
  tauBookPro: '/products/tau-book-pro',
  tauTablet: '/products/tau-tablet',
  tauWatch: '/products/tau-watch',
  tauGlass: '/products/tau-glass',
  tauBrowser: '/taubrowser',
  tauMail: '/taumail',
  tauMailLogin: '/taumail/login',
  tauMailRegister: '/taumail/register',
  tauTalk: '/tautalk',
  tauDrive: '/products/tau-drive',
  tauIde: '/developers',
  tauAi: '/tauai',
  /** Tau AI product app (Figma UI) — welcome → auth → home */
  tauAiApp: '/tau-ai-app/welcome',
  tauAiLogin: '/tau-ai-app/auth',
  tauCloud: '/taucloud',
  tauId: '/tauid',
  tauIdLogin: '/tauid/login',
  tauIdRegister: '/tauid/register',
  tauStore: '/taustore',
  projectGrayscale: '/products/project-grayscale',
  tauStartup: '/products/tau-startup',
  enterprise: '/enterprise',
  developer: '/developers',
  docs: '/developers/docs',
  download: '/download',
  downloads: '/downloads',
  roadmap: '/roadmap',
  about: '/about',
  careers: '/careers',
  press: '/press',
  contact: '/contact',
  help: '/help',
  status: '/status',
  governance: '/governance',
  privacy: '/legal/privacy',
  terms: '/legal/terms',
  cookies: '/legal/cookies',
  security: '/enterprise/security',
  login: '/developers/login',
  register: '/developers/register',
  experience: '/#experience',
  community: '/#community',
} as const;

export type WebsiteRouteKey = keyof typeof websiteRoutes;

export const footerLinks = {
  products: [
    { label: 'Tau Core', href: websiteRoutes.tauCore },
    { label: 'Tau Phone', href: websiteRoutes.tauPhone },
    { label: 'Tau Book Pro', href: websiteRoutes.tauBookPro },
    { label: 'Tau Browser', href: websiteRoutes.tauBrowser },
    { label: 'Tau Mail', href: websiteRoutes.tauMail },
    { label: 'Tau Talk', href: websiteRoutes.tauTalk },
    { label: 'Tau Drive', href: websiteRoutes.tauDrive },
    { label: 'Tau IDE', href: websiteRoutes.tauIde },
    { label: 'Tau AI', href: websiteRoutes.tauAi },
    { label: 'Tau Cloud', href: websiteRoutes.tauCloud },
  ],
  company: [
    { label: 'About', href: websiteRoutes.about },
    { label: 'Careers', href: websiteRoutes.careers },
    { label: 'Press', href: websiteRoutes.press },
    { label: 'Contact', href: websiteRoutes.contact },
    { label: 'Newsroom', href: websiteRoutes.press },
  ],
  developers: [
    { label: 'Documentation', href: websiteRoutes.docs },
    { label: 'APIs', href: websiteRoutes.docs },
    { label: 'SDKs', href: websiteRoutes.docs },
    { label: 'GitHub', href: 'https://github.com/TheDotProtocol/tauos' },
    { label: 'Developer Blog', href: websiteRoutes.docs },
  ],
  support: [
    { label: 'Help Center', href: websiteRoutes.help },
    { label: 'Community', href: websiteRoutes.community },
    { label: 'Status', href: websiteRoutes.status },
    { label: 'Accessibility', href: websiteRoutes.help },
  ],
  legal: [
    { label: 'Privacy Policy', href: websiteRoutes.privacy },
    { label: 'Terms of Use', href: websiteRoutes.terms },
    { label: 'Cookie Policy', href: websiteRoutes.cookies },
    { label: 'Security', href: websiteRoutes.security },
    { label: 'Responsible Disclosure', href: websiteRoutes.contact },
    { label: 'Compliance', href: websiteRoutes.governance },
  ],
  resources: [
    { label: 'Brand Guidelines', href: websiteRoutes.about },
    { label: 'Legal Documentation', href: websiteRoutes.privacy },
    { label: 'Payment Policy', href: websiteRoutes.terms },
  ],
} as const;
