[package]
name = "test-tauui"
version = "0.1.0"
edition = "2021"
authors = ["Tau OS Developer"]
description = "A Tau OS application"

[dependencies]
anyhow = "1.0"
log = "0.4"
env_logger = "0.10"

[[bin]]
name = "test-tauui"
path = "src/main.rs"
