[package]
name = "taustore-frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = "0.7"
gio = "0.17"
glib = "0.17"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
taukit = { path = "../../gui/taukit" } 