# Dynamic Traefik Configuration for TauMail
http:
  middlewares:
    security-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"
        contentSecurityPolicy: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:; frame-ancestors 'self';"
        referrerPolicy: "strict-origin-when-cross-origin"
        permissionsPolicy: "camera=(), microphone=(), geolocation=()"

  routers:
    taumail-webmail:
      rule: "Host(`mail.arholdings.group`)"
      service: taumail-webmail
      tls:
        certResolver: letsencrypt
      middlewares:
        - security-headers

  services:
    taumail-webmail:
      loadBalancer:
        servers:
          - url: "http://taumail-webmail:3000" 