# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

$RNFirebaseAsStaticFramework = true

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'TauMailMobile' do
  config = use_native_modules!

  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'TauMailMobileTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # RN 0.72 + Xcode 16+: Yoga literal-operator deprecation is treated as error (-Werror).
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        build_config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
        build_config.build_settings['OTHER_CPLUSPLUSFLAGS'] ||= ['$(inherited)']
        build_config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-Wno-error=deprecated-literal-operator'
        build_config.build_settings['OTHER_CFLAGS'] ||= ['$(inherited)']
        build_config.build_settings['OTHER_CFLAGS'] << '-Wno-error=deprecated-literal-operator'

        # Newer iOS SDK defines clockid_t; avoid RCT-Folly typedef clash.
        build_config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        unless build_config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'].include?('FOLLY_HAVE_CLOCK_GETTIME=1')
          build_config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FOLLY_HAVE_CLOCK_GETTIME=1'
        end
      end
    end
  end
end
