#!/bin/bash

# TauOS Domain Configuration Script
# This script helps configure the custom domain for tauos.org

echo "🌐 Configuring TauOS Domain..."

# Get the current Vercel deployment URL
DEPLOYMENT_URL=$(vercel ls --json | jq -r '.deployments[0].url')

echo "✅ Current deployment URL: $DEPLOYMENT_URL"
echo ""
echo "📋 Next Steps to Configure tauos.org:"
echo ""
echo "1. Add Custom Domain in Vercel:"
echo "   - Go to: https://vercel.com/dashboard"
echo "   - Select your TauOS project"
echo "   - Go to Settings → Domains"
echo "   - Add: tauos.org"
echo ""
echo "2. Configure DNS in Squarespace:"
echo "   - Log into your Squarespace account"
echo "   - Go to Settings → Domains"
echo "   - Select tauos.org"
echo "   - Add DNS records:"
echo ""
echo "   A Record:"
echo "     Name: @"
echo "     Value: [Vercel IP - will be provided by Vercel]"
echo ""
echo "   CNAME Record:"
echo "     Name: www"
echo "     Value: $DEPLOYMENT_URL"
echo ""
echo "3. Wait for DNS Propagation (5-10 minutes)"
echo ""
echo "4. Test the domain:"
echo "   - https://tauos.org"
echo "   - https://www.tauos.org"
echo ""
echo "🎉 Once configured, your website will be live at:"
echo "   https://tauos.org"
echo ""
echo "SSL certificates will be automatically generated by Vercel!" 