#!/bin/bash

# TauOS GitHub Setup Script
# This script helps set up the GitHub repository and push the code

echo "🚀 Setting up TauOS GitHub Repository..."

echo ""
echo "📋 Steps to create GitHub repository:"
echo ""
echo "1. Go to https://github.com/new"
echo "2. Repository name: tauos"
echo "3. Description: Privacy-first operating system built for the modern user"
echo "4. Make it Public"
echo "5. Don't initialize with README (we already have one)"
echo "6. Click 'Create repository'"
echo ""
echo "2. After creating the repository, run these commands:"
echo ""
echo "   # Add the remote (replace YOUR_USERNAME with your GitHub username)"
echo "   git remote set-url origin https://github.com/YOUR_USERNAME/tauos.git"
echo ""
echo "   # Push the code"
echo "   git push -u origin main"
echo ""
echo "3. Once pushed, you can import to Vercel:"
echo ""
echo "   - Go to https://vercel.com/new"
echo "   - Import Git repository"
echo "   - Select your tauos repository"
echo "   - Set root directory to: website"
echo "   - Deploy"
echo ""
echo "4. Configure custom domain:"
echo ""
echo "   - In Vercel dashboard, go to Settings → Domains"
echo "   - Add: tauos.org"
echo "   - Configure DNS in Squarespace"
echo ""
echo "🎉 Your TauOS repository will be live and ready for the world!"
echo ""
echo "Repository URL will be: https://github.com/YOUR_USERNAME/tauos"
echo "Website URL will be: https://tauos.org" 