import { Lexer } from './lexer';
import { Parser } from './parser';
import type { ASTNode, FunctionDefNode, StructDefNode, EnumDefNode } from './ast';
import { listModules, getModule } from './stdlib';

export type DocEntry = {
  kind: 'function' | 'struct' | 'enum' | 'module' | 'trait' | 'interface';
  name: string;
  signature?: string;
  description: string;
  line?: number;
};

export type DocResult = {
  title: string;
  entries: DocEntry[];
  markdown: string;
  html: string;
};

function docFunction(fn: FunctionDefNode): DocEntry {
  const asyncKw = fn.async ? 'async ' : '';
  const generics = fn.typeParams?.length ? `<${fn.typeParams.join(', ')}>` : '';
  return {
    kind: 'function',
    name: fn.name,
    signature: `${asyncKw}fn ${fn.name}${generics}(${fn.params.join(', ')})`,
    description: `Function \`${fn.name}\` with ${fn.params.length} parameter(s).`,
    line: fn.line,
  };
}

function entriesFromAst(ast: ASTNode[]): DocEntry[] {
  const entries: DocEntry[] = [];
  for (const node of ast) {
    if (node.type === 'functionDef') entries.push(docFunction(node));
    if (node.type === 'structDef') {
      entries.push({
        kind: 'struct',
        name: node.name,
        signature: `struct ${node.name}`,
        description: `Struct with fields: ${node.fields.map((f) => f.name).join(', ')}`,
        line: node.line,
      });
    }
    if (node.type === 'enumDef') {
      entries.push({
        kind: 'enum',
        name: node.name,
        signature: `enum ${node.name}`,
        description: `Enum variants: ${node.variants.join(', ')}`,
        line: node.line,
      });
    }
    if (node.type === 'traitDef') {
      entries.push({
        kind: 'trait',
        name: node.name,
        signature: `trait ${node.name}`,
        description: `Trait with methods: ${node.methods.map((m) => m.name).join(', ')}`,
        line: node.line,
      });
    }
    if (node.type === 'interfaceDef') {
      entries.push({
        kind: 'interface',
        name: node.name,
        signature: `interface ${node.name}`,
        description: `Interface with methods: ${node.methods.map((m) => m.name).join(', ')}`,
        line: node.line,
      });
    }
  }
  return entries;
}

function toMarkdown(title: string, entries: DocEntry[]): string {
  const lines = [`# ${title}`, '', `Generated by \`tau doc\` — TauScript v1.0`, ''];
  for (const e of entries) {
    lines.push(`## ${e.kind}: ${e.name}`);
    if (e.signature) lines.push('', '```tau', e.signature, '```');
    lines.push('', e.description, '');
  }
  // Stdlib modules
  lines.push('## Standard Library', '');
  for (const mod of listModules()) {
    const exports = getModule(mod);
    lines.push(`### ${mod}`, '');
    if (exports) {
      Array.from(exports.keys()).forEach((name) => {
        lines.push(`- \`${name}\``);
      });
    }
    lines.push('');
  }
  return lines.join('\n');
}

function toHtml(markdown: string): string {
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>TauScript Docs</title>
<style>body{font-family:system-ui;max-width:800px;margin:2rem auto;padding:0 1rem;background:#0a0a0a;color:#e0e0e0}
h1,h2{color:#22d3ee}code{background:#1a1a1a;padding:2px 6px;border-radius:4px}</style></head>
<body><pre>${markdown.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</pre></body></html>`;
}

export function generateDocs(source: string, title = 'TauScript Module'): DocResult {
  const lexer = new Lexer(source);
  const ast = new Parser(lexer.tokenize()).parse();
  const entries = entriesFromAst(ast);
  const markdown = toMarkdown(title, entries);
  return { title, entries, markdown, html: toHtml(markdown) };
}

export function generatePackageDocs(files: Array<{ path: string; content: string }>, packageName: string): DocResult {
  const allEntries: DocEntry[] = [];
  for (const f of files) {
    const lexer = new Lexer(f.content);
    const ast = new Parser(lexer.tokenize()).parse();
    entriesFromAst(ast).forEach((e) => allEntries.push({ ...e, name: `${f.path}::${e.name}` }));
  }
  const markdown = toMarkdown(packageName, allEntries);
  return { title: packageName, entries: allEntries, markdown, html: toHtml(markdown) };
}
