version: '3.8'

services:
  # TauMail Webmail Application
  taumail-webmail:
    build:
      context: ./webmail
      dockerfile: Dockerfile
    container_name: taumail-webmail
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://taumail:taumail@postgres:5432/taumail
    depends_on:
      - redis
      - postgres
    networks:
      - taumail-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.taumail.rule=Host(`mail.arholdings.group`)"
      - "traefik.http.routers.taumail.tls=true"
      - "traefik.http.routers.taumail.tls.certresolver=letsencrypt"
      - "traefik.http.services.taumail.loadbalancer.server.port=3000"

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: taumail-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: taumail
      POSTGRES_USER: taumail
      POSTGRES_PASSWORD: taumail_secure_password_2025
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - taumail-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: taumail-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass taumail_redis_password_2025
    volumes:
      - redis_data:/data
    networks:
      - taumail-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: taumail-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - taumail-webmail
    networks:
      - taumail-network

  # Certbot for SSL Certificates
  certbot:
    image: certbot/certbot
    container_name: taumail-certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/html --email admin@arholdings.group --agree-tos --no-eff-email -d mail.arholdings.group -d arholdings.group
    depends_on:
      - nginx
    networks:
      - taumail-network

  # Traefik for SSL and Load Balancing
  traefik:
    image: traefik:v2.10
    container_name: taumail-traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - certbot-etc:/etc/letsencrypt:ro
    networks:
      - taumail-network

  # Mail Server (Postfix + Dovecot)
  mail-server:
    image: tvial/docker-mailserver:latest
    container_name: taumail-mail-server
    restart: unless-stopped
    ports:
      - "25:25"
      - "587:587"
      - "993:993"
      - "995:995"
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ONE_DIR=1
      - DMS_DEBUG=0
      - ENABLE_SSL_TLS=1
      - SSL_TYPE=letsencrypt
    volumes:
      - mail_data:/var/mail
      - mail_state:/var/mail-state
      - mail_logs:/var/log/mail
      - ./mailserver/config:/tmp/docker-mailserver:ro
      - certbot-etc:/etc/letsencrypt:ro
    networks:
      - taumail-network

  # Monitoring with Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: taumail-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - taumail-network

  # Grafana Dashboard
  grafana:
    image: grafana/grafana:latest
    container_name: taumail-grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=taumail_grafana_password_2025
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources:ro
    networks:
      - taumail-network

volumes:
  postgres_data:
  redis_data:
  mail_data:
  mail_state:
  mail_logs:
  prometheus_data:
  grafana_data:
  certbot-etc:
  certbot-var:

networks:
  taumail-network:
    driver: bridge 