name: Deploy to Vercel (Optional)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-taucloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Vercel CLI
        run: npm install -g vercel@latest
        
      - name: Deploy TauCloud to Vercel
        run: |
          cd vercel-tauos-cloud
          if [ -n "$VERCEL_TOKEN" ]; then
            echo "Deploying to Vercel..."
            vercel --token $VERCEL_TOKEN --prod --yes
          else
            echo "No VERCEL_TOKEN found. Skipping Vercel deployment."
            echo "Using Railway deployment instead."
          fi
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          
  deploy-taumail:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Vercel CLI
        run: npm install -g vercel@latest
        
      - name: Deploy TauMail to Vercel
        run: |
          cd vercel-tauos-mail
          if [ -n "$VERCEL_TOKEN" ]; then
            echo "Deploying to Vercel..."
            vercel --token $VERCEL_TOKEN --prod --yes
          else
            echo "No VERCEL_TOKEN found. Skipping Vercel deployment."
            echo "Using Railway deployment instead."
          fi
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }} 