name: Deploy to Vercel (Optional)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-taucloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Vercel CLI
        run: npm install -g vercel@latest
        
      - name: Deploy TauCloud to Vercel
        run: |
          cd vercel-tauos-cloud
          echo "Vercel deployment skipped - using Railway instead"
          echo "To enable Vercel deployment, configure VERCEL_TOKEN in GitHub secrets"
          echo "Current deployment: Railway (https://railway.app)"
          
  deploy-taumail:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Vercel CLI
        run: npm install -g vercel@latest
        
      - name: Deploy TauMail to Vercel
        run: |
          cd vercel-tauos-mail
          echo "Vercel deployment skipped - using Railway instead"
          echo "To enable Vercel deployment, configure VERCEL_TOKEN in GitHub secrets"
          echo "Current deployment: Railway (https://railway.app)" 